# Numbers and `numpy`

## Introduction

Last week, we began to explore the idea of "packages" that could help unlock additional functionality within python, such as `math`. These fall within the "standard library" - i.e. the built-in packages that come included when you install Python.

The strength of Python is that people can build their own packages. A foundation of the Python community is that they are often "open source", which means that they are freely available for people to use, edit, and contribute to. Open source is said to be "free" in two ways: the first, as in beer, and the second, as in speech. This means not only is the software available without any monetary cost (i.e. free beer), but you are free to do as you like to it with no restrictions - adapt it, remix it, and share it (i.e. free speech). Compare this, to, say, Microsoft Word: not only is it not free, but changing it and passing it on will get you into legal trouble! This course itself is open source - I have released the text under a [Creative Commons 4.0 International License](https://creativecommons.org/licenses/by/4.0/). You can do what you like with this content, so long as you attribute me correctly, and not suggest that I endorse any changes you might make. The code is released under an [MIT License](https://opensource.org/license/mit), which has a similar ethos with an extra-explicit caveat that I'm not liable if you use the code and it causes you any problems...

Lots of people have released lots of helpful open-source packages that we can use to do help us in our science. This week, we will introduce ourselves to a few select packages that form the foundation of this scientific python ecosystem: `numpy`, for advanced numerical analysis; `pandas`, for tabular data (think Excel!); and `matplotlib`, for plotting.

Last week, we used `conda` to install a number of these packages. However, if this isn't working for you now, or if you want to install different software, just make sure you have activated the correct environment within your command prompt, and install as follows:

```bash
conda activate gsc
conda -c conda-forge install numpy
```

"`conda-forge`" is the specific "storefront" we want to load our items from; `numpy` is the example software we wish to install.

## What's wrong with built-in functionality?

 The package we are examining in this section -- `numpy` -- is the foundation of everything else we built in scientific python. It allows us to do 'proper maths'.

 But wait -- didn't we do maths last week? We even imported a `math` module that allowed us to do more advanced things!

In [1]:
import math

Indeed, `math` has [quite an extensive library of functions](https://docs.python.org/3/library/math.html) that we can explore:

In [2]:
# Calculate e raised to the power of 5

result = math.exp(5)
print(f"e^5 = {result}")

e^5 = 148.4131591025766


In [3]:
# Convert from degrees to radians

degrees = 45
radians = math.radians(degrees)

print(f"{degrees} degrees is equal to {radians} radians")

45 degrees is equal to 0.7853981633974483 radians


In [4]:
# calculate the cosine of 60 degrees

cosine_60 = math.cos(math.radians(60))

print(f"The cosine of 60 degrees is {cosine_60}")

The cosine of 60 degrees is 0.5000000000000001


The main problem is that the standard data types available to us aren't naturally good at doing large mathematical operations. Let's, for example, imagine we have some temperatures in degrees celcius (in a `list` form), and want to convert them to Kelvin:

In [5]:
temperatures_c = [18.2, 19.1, 20.5, 21.0]

In [6]:
temperatures_k = temperatures_c + 273.15

TypeError: can only concatenate list (not "float") to list

Uh oh. Python has thrown an error! It doesn't care what's inside the list (be they strings, integers, dictionaries, etc...), so it doesn't know what we mean when we try and "add one to a list". For instance, it could be an equally valid interpretation that we want to append the value `1` to the end of the list, for instance (equal to `temperatures_c.append(1)`).

Okay, let's take another route. If the `list` capability isn't sure what we mean when we add a single number, why not create a list of equal length, all of `273.15`. Then, we will be able to add each element of one list to each element of another. This makes sense, right?

In [ ]:
add_kelvin = [273.15, 273.15, 273.15, 273.15]

temperatures_k = temperatures_c + add_kelvin

temperatures_k

[18.2, 19.1, 20.5, 21.0, 273.15, 273.15, 273.15, 273.15]

Oh dear, this still isn't what we want! Python thinks that "adding" lists together means _concatenating_ lists, because lists are designed to handle all types of objects, not just numbers.

In fact, the easiest way to perform this is probably to loop through every temperature individually, adding values:

In [ ]:
temperatures_k = []

for t in temperatures_c:
    temperatures_k.append(t + 273.15)

temperatures_k

[291.34999999999997, 292.25, 293.65, 294.15]

This isn't convenient at all for such a simple operation! Additionally, this is _expensive_: we all have very advanced computers nowadays, but in this loop format, our computer will try and solve these operations one-by-one. We can use a special Notebook function called `%%time` to show us how long each cell takes to run. Let's try and calculate a square root a large amount of times - say, 50 million.

In [ ]:
%%time

n_sqrt = []

for n in range(50_000_000):  # Underscores in numbers are just for readability, they don't affect the value
    n_sqrt.append(math.sqrt(n))


CPU times: user 1.92 s, sys: 338 ms, total: 2.25 s
Wall time: 2.26 s


On my laptop, it takes 1.89 seconds to calculate a square root 50 million times. This might seem impressive, but, as we will show later, it is trivial compared to what modern computing is capable of!

We need a tool that allows us to operate more easily on large numerical datasets.


## The ease of `numpy`

Let's start using `numpy` instead of built-in Python and `math`.

In [8]:
import numpy as np

`numpy`, conventionally shortened to `np` when importing, introduces another type of object: the numpy array.

In [9]:
temperatures_c = np.array([18.2, 19.1, 20.5, 21.0])

temperatures_c

array([18.2, 19.1, 20.5, 21. ])

Unlike lists, which happily accept all data types, numpy arrays accept numbers, and only numbers. What's more, they have to be of a single type - you can't mix integers and floats, as we were doing before.

This might seem like it things less flexible than lists. However, because we know that everything inside an array is numerical, `numpy` can accept what instict said would be a 'sensible' way approaching operations from before. For instance, we can add a single value to the whole list:

In [10]:
temperatures_c + 273.15

array([291.35, 292.25, 293.65, 294.15])

It will also allow you to add two arrays of equal size, so all our approaches will work!

In [ ]:
add_kelvin = np.array([273.15, 273.15, 273.15, 273.15])

temperatures_c + add_kelvin

array([291.35, 292.25, 293.65, 294.15])

Another key factor to understand is that numpy is _vectorising_ our operations. This means we are computing entire sets of values at once, rather than explitly _looping through these lists one at a time_ like we were doing before.

We can see the difference when doing the same thing as we were doing before: calculating the square root of 50 million numbers. This time, we use custom `numpy` functions: `np.arange()` to generate a numpy array rather than `range`; and `np.sqrt` to apply a square root to a whole numpy array, rather than using `math.sqrt()` one at a time.

In [ ]:
%%time 
numbers_arr = np.arange(50_000_000)
numbers_sqrt_np = np.sqrt(numbers_arr)

CPU times: user 49.7 ms, sys: 69.7 ms, total: 119 ms
Wall time: 128 ms


This took only ~150 ms (0.15s) rather than 1.89s! This is a relatively crude test, and also included the _generation_ of 50 million numbers. In practice, speed ups can be even faster in a lot of situations.

### Numpy array characteristics

We can inspect a number of potential characteristics of our numpy array, such as the number of dimensions (`ndim`) and the length of those dimensions (`shape`):

In [ ]:
a = np.array([1, 2, 3, 4])

print(a.ndim)
print(a.shape)

1
(4,)


Our array has one dimension, which has a length four.

This doesn't appear particularly useful, but numpy arrays can be $n$-dimensional - for instance, here is a 2D array:

In [11]:
b = np.array([[1, 2, 3], [4, 5, 6]])

print(b)

print('Number of dimensions:', b.ndim)
print('Shape:', b.shape)

[[1 2 3]
 [4 5 6]]
Number of dimensions: 2
Shape: (2, 3)


Our 2-D array has arrays of length 2 and 3.

We can also explore the data type of a numpy array, through `dtype`:

In [ ]:
b.dtype

dtype('int64')

This shows that is a 64-bit integer. This means the maximum value this data type could hold is 2<sup>64</sup>, which is --

In [ ]:
2**64

18446744073709551616

-- quite large! If we had a very very large array and were worried about file sizes, we could instead select a smaller data type, such as `int32` or even `int8`. `int8` stores 2<sup>8</sup>, or 256, values (this value might seem familiar from various interactions with computers over the years!). Many old digital satellite images are stored in 8-bit colour scale, with a single value between 0 and 255. So there's no point storing old satellite data with more precision than this - you're just wasting file space!

You can change data types using `astype`. Let's change this to a 32-bit float.

In [13]:
c = b.astype(np.float32)  # 'astype' will also accept a suitable string representation of the data type, e.g., 'float32', 'int64', etc.

print(c)

print(c.dtype)

[[1. 2. 3.]
 [4. 5. 6.]]
float32


### Generating numpy arrays

We know about the existing `range()` function, but numpy has its own functions - one of which we used above. These have some nice additional functionality, such as stepping within the `np.arange(start, stop, step)` function:

In [ ]:
d = np.arange(1, 10, 2)  # Start at 1, go up to (but not including) 10, step by 2

d

array([1, 3, 5, 7, 9])

`linspace(start, stop, num)` allows us to create a range of `num` evenly spaced values between `start` and `stop`:

In [15]:
e = np.linspace(0, 10, 21)  # Start at 0, go up to (and include) 10, with 21 evenly spaced points (i.e. every 0.5)

e

array([ 0. ,  0.5,  1. ,  1.5,  2. ,  2.5,  3. ,  3.5,  4. ,  4.5,  5. ,
        5.5,  6. ,  6.5,  7. ,  7.5,  8. ,  8.5,  9. ,  9.5, 10. ])

### Constants and Functions

As under `math`, `numpy` has a standard range of constants and functions available to you. Here are some examples of things you can do, mixed with approaches we learned last week: see if you can understand what's going on.

In [ ]:
print(np.pi)

3.141592653589793


In [17]:
x = np.linspace(0, 2 * np.pi, 10)  # Create an array of 10 evenly spaced values from 0 to 2π

y = np.sin(x)  # Calculate the sine of each value in x


for x_i, y_i in zip(x, y):  # "zip" combines the two arrays into pairs of (x, y) values

    # Print the x and sin(x) values, formatted to 2 decimal places
    print(f"x: {x_i:.2f}, sin(x): {y_i:.2f}")  # adding ":.2f" to an f-string formats the number to 2 decimal places

x: 0.00, sin(x): 0.00
x: 0.70, sin(x): 0.64
x: 1.40, sin(x): 0.98
x: 2.09, sin(x): 0.87
x: 2.79, sin(x): 0.34
x: 3.49, sin(x): -0.34
x: 4.19, sin(x): -0.87
x: 4.89, sin(x): -0.98
x: 5.59, sin(x): -0.64
x: 6.28, sin(x): -0.00


In [18]:
# Round y to three decimal places
y_rounded = np.round(y, 3)

print("y (original):", y)
print("y (rounded to 3 decimal places):", y_rounded)

y (original): [ 0.00000000e+00  6.42787610e-01  9.84807753e-01  8.66025404e-01
  3.42020143e-01 -3.42020143e-01 -8.66025404e-01 -9.84807753e-01
 -6.42787610e-01 -2.44929360e-16]
y (rounded to 3 decimal places): [ 0.     0.643  0.985  0.866  0.342 -0.342 -0.866 -0.985 -0.643 -0.   ]


In [19]:
# Convert between radians and degrees

x_deg = np.rad2deg(x)  # x ranges from 0 to 2π, so after converting from radians to degrees, x_deg should range from 0 to 360 degrees

x_deg

array([  0.,  40.,  80., 120., 160., 200., 240., 280., 320., 360.])

In [20]:
# Calculate the sum, and cumulative sum, of a sequence of numbers

z = np.arange(1, 11)  # Create an array of numbers from 1 to 10

z_sum = np.sum(z)  # Calculate the sum of the elements in z

z_cumsum = np.cumsum(z)  # Calculate the cumulative sum of the elements in z

print(f"z: {z}")
print(f"Sum of z: {z_sum}")
print(f"Cumulative sum of z: {z_cumsum}")

z: [ 1  2  3  4  5  6  7  8  9 10]
Sum of z: 55
Cumulative sum of z: [ 1  3  6 10 15 21 28 36 45 55]


In [ ]:
# Calcualte statistics of an array

w = np.random.rand(100)  # Create an array of 1000 random numbers between 0 and 1

w_mean = np.mean(w)  # Mean

w_std = np.std(w)  # Standard deviation

w_median = np.median(w)  # Median

print(f"Mean of w: {w_mean}")
print(f"Standard deviation of w: {w_std}")
print(f"Median of w: {w_median}")

Mean of w: 0.4840792246964705
Standard deviation of w: 0.288983979143806
Median of w: 0.47768185503924965


In [ ]:
# Use some conditional logic to filter an array

w = np.random.rand(10)  # Create an array of 100 random numbers between 0 and 1

w_mask = w > 0.5  # Select only the elements of w that are greater than 0.5

print("w_mask shows True where the condition is met and False where it is not:", w_mask)

w_filtered = w[w > 0.5]  # Use the mask to filter the array

print("We can filter to show only elements of w that are greater than 0.5:", w_filtered)


w_mask shows True where the condition is met and False where it is not: [ True  True False False False False  True False  True  True]
We can filter to show only elements of w that are greater than 0.5: [0.82277008 0.99718565 0.85526962 0.90252714 0.93461197]


It would be impossible to cover the full breadth of what `numpy` can do within the span of this course: instead, I direct you to the [`numpy` documentation for reference](https://numpy.org/doc/stable/), which has some very nice beginners guides. 

You shouldn't be expected to know all of `numpy` (nor `pandas`, nor any tool we are going to learn in this course): the correct course of action is:

1. Knowing what tool might be appropriate to solve your problem.
2. Knowing how to search for the information (e.g. asking Google or LLMs "how can I use numpy to calculate the cosine?")
3. Understanding how to integrate the answer you find with your existing code.

In the coming exercises, I may direct you to do this more: tell you that something is possible, and asking you to implement the solution yourself using your own initative.

### Indexing and Slicing

As with lists, we can use indexing to pull out individual elements. This can be more confusing for multidimensional arrays. Let's create a 2-dimensional array, using the `reshape` function:

In [ ]:
f = np.arange(12).reshape(3, 4)  # Create a 3x4 array
f

array([[ 0,  1,  2,  3],
       [ 4,  5,  6,  7],
       [ 8,  9, 10, 11]])

Recall that Python indexing starts at `0`: if we select the first element, we will get:

In [ ]:
f[0]

array([0, 1, 2, 3])

Looking at how our array is structured above, this makes some sense: our n-dimensional array is basically an 1-D array made up of three arrays. So `f[0]` brings out this first array. 

We can further pull out a specific item in this array:

In [ ]:
f[0, 2]  # Select the first row and the third column

np.int64(2)

In [ ]:
f[-1, -3]  # Select the last row and the third-to-last column

np.int64(9)

Play around with this multi-dimensional indexing until you feel comfortabl ewith what is going on.

We can also extract ranges of data using slices. We did this previously to lists, but again, we can do _multidimensional_ slicing by repeating our instruction for the row, and then the column:

In [ ]:
f[0:2, 0:2]  # Select the first two rows and the first two columns

array([[0, 1],
       [4, 5]])

In [ ]:
f[0:2, ::]  # Select the first two rows and all columns (note the special "::" syntax)

array([[0, 1, 2, 3],
       [4, 5, 6, 7]])

Several functions allow us to provide an axis, so that operations can be performed only in one direction. For instance, instead of the default `sum`, we can direct the sum along specific axes. Remember that, within `numpy` convention, axis `0` is along-column, and axis `1` is along-row.

In [ ]:
print(f.sum())  # Calculate the sum of all elements in the array f

print(f.sum(axis=0))  # Calculate the sum of each column

print(f.sum(axis=1))  # Calculate the sum of each row

66
[12 15 18 21]
[ 6 22 38]


## Summary

We have been introduced to `numpy`, a very powerful toolkit that allows us to efficiently perform mathematical operations on large arrays of numbers.

Next, we will see how we can begin to plot large datasets to better visualise them.