# Numbers and `numpy`

Last week, we began to explore the idea of "packages" that could help unlock additional functionality within python, such as `math` and `os`. These fall within the "standrd library" - i.e. the built-in packages that come when you install Python.

The strength of Python is that people can build their own packages. A foundation of the Python community is that they are often "Open Source", which means...

Last week, you may have noticed we installed a number of additional things alongside Python. The first of these was `numpy`, which is the best place to start when exploring the scientific python ecosystem. `numpy` is the foundation of everything else we are looking at - it allows us to do 'proper maths'.

## What's wrong with standard python for maths?

Standard python does give us some mathematical capability, primarily through the `math` module:

In [ ]:
import math

# show some simple examples of what you can do here

The main problem is that the standard data types available to us aren't naturally good at doing large mathematical operations. Let's, for example, imaging we have some temperatures in celcius (in a `list` form), and want to convert them to kelvin:

In [15]:
temperatures_c = [18.2, 19.1, 20.5, 21.0]

In [16]:
temperatures_k = temperatures_c + 273.15

TypeError: can only concatenate list (not "float") to list

Uh oh. Python has thrown an error! It doesn't care what's inside the list (be they strings, integers, dictionaries, etc...), so it doesn't know what we mean when we try and "add one to a list".

Okay, let's take another tack. Let's create a list of equal length, and try and add each element together. This makes sense, right?

In [6]:
add_kelvin = [273.15, 273.15, 273.15, 273.15]

temperatures_k = temperatures_c + add_kelvin

temperatures_k

[18.2, 19.1, 20.5, 21.0, 273.15, 273.15, 273.15, 273.15]

This still isn't what we want! Python thinks that "adding" lists together means _concatenating_ lists, because lists are designed to handle all types of objects, not just numbers.

In fact, the easiest way to perform this is probably to loop through every temperature individually, adding values:

In [8]:
temperatures_k = [t + 273.15 for t in temperatures_c]

temperatures_k

[291.34999999999997, 292.25, 293.65, 294.15]

This isn't convenient at all. We need a tool that allows us to operate more easily on large numerical datasets.

## `numpy`

In [9]:
import numpy as np

`numpy`, conventionally shortened to `np` when importing, introduces another type of object: the numpy array.

In [17]:
temperatures_c = np.array([18.2, 19.1, 20.5, 21.0])

temperatures_c

array([18.2, 19.1, 20.5, 21. ])

Because we know that everything inside an array is numerical, our instinctive operations from before work:

In [13]:
temperatures_c + 274.15

array([292.35, 293.25, 294.65, 295.15])

In [18]:
add_kelvin = np.array([273.15, 273.15, 273.15, 273.15])

temperatures_c + add_kelvin

array([291.35, 292.25, 293.65, 294.15])

Another key factor to understand is that now, when we're doing these operations, we aren't _looping through these lists one at a time_. We're 